# api/config/packages/vich_uploader.yaml
vich_uploader:
    db_driver: orm
    metadata:
        type: attribute
    mappings:
        media_file:
            uri_prefix: /file
            upload_destination: '%kernel.project_dir%/public/file'
            namer: Vich\UploaderBundle\Naming\SlugNamer
