# api/config/packages/vich_uploader.yaml
vich_uploader:
    db_driver: orm
    metadata:
        type: attribute
    mappings:
        media_file:
            uri_prefix: /media/images
            upload_destination: '%kernel.project_dir%/media/images'
            namer: Vich\UploaderBundle\Naming\SlugNamer